### PR TITLE
fix: 🐛 change dependencies for TS

### PR DESCRIPTION
**Pull request by muenzpraeger**

### CODE REVIEW

**Comment by muenzpraeger** [comment]
Not sure what type of test you recommend, @trevor-bliss.

**Comment by muenzpraeger** [comment]
Slimming down - got it. I duplicated the existing ones, for consistency. Will update.

**Comment by muenzpraeger** [comment]
@trevor-bliss Added simplified test cases.

**Comment by aputinski** [comment]
When is the next release due to be published? And will this be included?

**Pull request merged**
